<div>
<img src="images/Screen Shot 2021-09-21 at 3.45.10 PM.png" width="1200" style="float:center"/>
</div>

# **Welcome to the Intro to Numpy + Pandas Workshop**
By Jillian Criscuolo, Aashritha Srirambhatla, Nayan Chavan, Mein Lee

In Collaboration with the Division of Data Science's [Data Peer Consulting](https://data.berkeley.edu/ds-peer-consulting)

### BEFORE WE BEGIN PLEASE COMPLETE THIS SURVEY
[Pre-Workshop Survey Link](https://docs.google.com/forms/d/e/1FAIpQLSeW_6oyWOlByhGUrVKTJvvQaQw4dHmvSXpJIF-dI5lxWzPO7g/viewform?usp=sf_link)  

## Jillian Criscuolo 
![Vincent](images/jillian_criscuolo_photo_-_jillian_criscuolo.jpg)

Quick Facts About Me:

    🐻 Senior at Cal
    🎒 Studying Data Science
    🏢 Interned as a Solutions Consultant Analyst @ Adobe
    📊 Joined the Data Peer Consulting team in Fall 2020

How to Reach Me:

    📮 Email: jcriscuolo@berkeley.edu

## Aashritha Srirambhatla
![Vincent](images/aashritha_srirambhatla_0.jpeg)

Quick Facts About Me:

    🐻 Junior at Cal
    🎒 Studying Data Science
    🏢 Interned as an Analyst @ Amazon
    📊 Joined the Data Peer Consulting team in Spring 2021

How to Reach Me:

    📮 Email: aashritha@berkeley.edu

## Nayan Chavan
![Vincent](images/4e86ab73-918d-4234-b13a-8cd37c0ec35b-bcbcee29-223d-472e-b616-111bb85c30fe_-_nayan_chavan-1.jpg)

Quick Facts About Me:

    🐻 Senior at Cal
    🎒 Studying Data Science with a minor in Computer Science
    🏢 Interned as a SWE @ Goldman Sachs
    📊 Joined the Data Peer Consulting team in Fall 2020

How to Reach Me:

    📮 Email: nayanchavan@berkeley.edu

## Mein Lee
![Vincent](images/c8782657-7ea5-4cd7-b83b-343e1201653f_-_mein_en_lee.jpeg)

Quick Facts About Me:

    🐻 Senior at Cal
    🎒 Studying Data Science
    🏢 Interned as an AWS ASEAN @ Amazon
    📊 Joined the Data Peer Consulting team in Spring 2021

How to Reach Me:

    📮 Email: meinlee@berkeley.edu

---

## Workshop Goals

The goal of this workshop is to cover the fundamentals of numpy and Pandas and give a working knowledge of these two major packages. By the end of the workshop, you should be able to fluently manipulate Numpy arrays, as well as be able to do basic (Excel/SQL style) table operations on data using Pandas. 

    - Understand the fundamental similarities and differences between Numpy arrays and Python lists as well as when to use one or the other. 
    - Apply the basic Pandas data structures as well as the basic table operations onto dataframes 
    - Demonstrate the basic workflow for intaking data and exploring it using Numpy and Pandas

<a class="anchor" id="tof"></a>
## Table of Contents

Use anchors to set these hyperlinks to jump to certain locations in the notebook. 

- [Numpy](#1)
- [Pandas](#2)
- [Reference Sheets](#rs)

---

<a class="anchor" id="1"></a>
## Numpy Fundamentals
[Back to Table of Contents](#tof)

NumPy stands for "Numerical Python". What this means is that Numpy is a package used for fast, efficient numerical calculations in Python. Numpy uses what we will call ***Numpy Arrays***, which are very similar to Python lists, but have a couple of key differences that we will take a look at.

To use the Numpy package (or any other package), we must always import it into whatever text editor (program used for coding, e.g. Jupyter Notebook) that we are using.

In [2]:
### Standard import statement for Numpy 

import numpy as np

We can now use the NumPy package with the shorthand `np`! We access various functions inside this package with `np.function(*arguments)`, where function() is the function you would like to use.

[Jump to Key Difference 3](#kd3)  
[Jump to Numpy Functions](#npfuncs)

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Without further ado, let's talk about the differences between NumPy arrays and Python lists!  

---

**Key Difference 1:** They have different data types.

In [4]:
# Python list
# The notation to create one is using square brackets. You can create an empty one like so:
list1 = []
type(list1)

list

In [5]:
# Numpy array
# Notice that by passing a Python list into the np.array() function as an argument, it turns it into a NumPy array!
array1 = np.array([])
type(array1)

numpy.ndarray

**Key Difference 2:** Python lists can contain any kind of data type, and keeps them the way they are. However, NumPy objects can only contain data of the same type.

In [6]:
list2 = ['any', 123, 'kind', 456, 'of', 123/456, 'data', True, 'type']
list2

['any', 123, 'kind', 456, 'of', 0.26973684210526316, 'data', True, 'type']

In [7]:
array2 = np.array(list2)
array2

array(['any', '123', 'kind', '456', 'of', '0.26973684210526316', 'data',
       'True', 'type'], dtype='<U19')

In [8]:
array2[1], list2[1]

('123', 123)

In [9]:
type(array2[1]), type(list2[1])

(numpy.str_, int)

How does NumPy determine which data type to turn everything into then? 

Out of the primitive* data types, there's a "data type hierarchy" so to speak. NumPy will turn all the entries into the most complex data type that it finds in the array. The hierarchy is as follows, from least complex to most complex:
- **Boolean < Integer < Float < String**

\**primitive data types: boolean - true/false, integer, float - decimal numbers, string - letters*

In [10]:
# some more examples
np.array([True, False, 1, 2, 3, 1.1, 2.2, 3.3]), np.array([True, False, 1, 2, 3])

(array([1. , 0. , 1. , 2. , 3. , 1.1, 2.2, 3.3]), array([1, 0, 1, 2, 3]))

- True values turn into 1
- False values turn into 0
- Integers get a decimal point
- Floats turn into strings, indicated by the quotation marks around them

**Key Difference 3 [Very Important] :** Numerical operations with Python lists has different behavior than adding NumPy arrays.  <a class="anchor" id="kd3"></a>

In [11]:
list3 = [1, 2, 3]
list4 = [1, 2, 3]
list3 + list4

[1, 2, 3, 1, 2, 3]

In [12]:
list3 - list4 # error is expected

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [13]:
list3 * list4 # error is expected

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
list3 / list4 # error is expected

In [ ]:
# note: we are not reassigning this value to list3, so the result we see printed out under this cell is not permanent
list3 + [4] 

In [ ]:
# What if we put strings inside the Python lists?
string_list1 = ['test', '1', '2', '3']
string_list2 = ['test', '4', '5', '6']
string_list1 + string_list2

---

Now with Numpy Arrays:

In [14]:
array3 = np.array(list3) # Q: What is happening here? A: Think about replacing "list3" with the value assigned to it!
array4 = np.array(list4)
array3 + array4

array([2, 4, 6])

In [15]:
array3 + 10 # automatically performs element-wise arithmetic: [1+10, 2+10, 3+10]

array([11, 12, 13])

In [16]:
array3 * 10 # [1*10, 2*10, 3*10]

array([10, 20, 30])

In [17]:
array3 - array4

array([0, 0, 0])

In [18]:
array3 * array4

array([1, 4, 9])

In [19]:
array3 / array4 # notice it automatically converts things to floats when we divide!

array([1., 1., 1.])

In [20]:
array3 ** array4 # ** denotes exponents, which also works for NumPy!

array([ 1,  4, 27], dtype=int32)

In [21]:
# What if we put strings inside the NumPy arrays? [Error expected]
string_array1 = np.array(['test', '1', '2', '3'])
string_array2 = np.array(['test', '4', '5', '6'])
string_array1 + string_array2

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U4') dtype('<U4') dtype('<U4')

In short, there are some limitations to both. 
- Python lists can hold multiple data types at a time, while NumPy arrays can only hold one data type at a time
- Adding Python lists *concatenates* them, while adding NumPy arrays performs element-wise addition
- Other operations on Python lists don't work, but any numerical operation works element-wise with NumPy arrays

---

Now, let's learn some very common NumPy array functions besides `np.array()`!

### Commonly Used NumPy Functions <a class="anchor" id="npfuncs"></a>
Here are the corresponding NumPy documentations for reference:
- [np.append](https://numpy.org/doc/stable/reference/generated/numpy.append.html)
- [np.arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)
- [np.linspace](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

Alternatively, when your typing line is hovering over a function, you can click `shift` + `tab` to open up the same documentation in Jupyter Notebook. Handy!

---
Since addition doesn't allow us to *concatenate* two NumPy arrays, we have to have another way to do so.
`np.append` does exactly that.

In [ ]:
# re-print the arrays for reference
array5 = np.array([4,5,6])
array4, array5, string_array1

In [ ]:
# np.append
np.append(array4, array5)

In [ ]:
# The data types still change accordingly after appending
np.append(array4, string_array1)

---

`np.arange` creates a list of numbers based on the arguments you pass in.

In [ ]:
# np.arange(start value, stop value, step size); stop value is not included!
# default start is 0, stop value is required (no default), default step size is 1 
np.arange(5)

In [ ]:
np.arange(0,5,1)

In [ ]:
np.arange(0,5,2)

In [ ]:
np.arange(2,6,2) # Before running this, try to predict what it will print out!

---

`np.linspace` creates a list of `n` values that are perfectly evenly spaced between `start value` and `stop value`, where `n = number of values`.

This is very handy for when you need to create visualizations, and you want your tick marks or bins to be perfectly spaced.

In [ ]:
# np.linspace(start value, stop value, number of values); the stop value IS included
np.linspace(1,10,10)

In [ ]:
np.linspace(1,10,9)

In [ ]:
# "number of values" has a default of 50
np.linspace(0, 10)

---

There are many functions that calculate various descriptive statistics as well. Note that you can pass in either a NumPy array or a Python list, as its argument.

- np.min
- np.max
- np.sum
- np.mean
- np.median
- np.std
- np.percentile

In [ ]:
numbers = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233]
np.min(numbers), np.max(numbers), np.sum(numbers)

In [ ]:
np.mean(numbers), np.std(numbers), np.median(numbers), np.percentile(numbers, 50) # 50th percentile = median

---

Another handy aspect of Numpy arrays is that they can be treated as vectors, allowing linear algebra operations such as dot product. 

- np.dot
- np.transpose

... and many more! You can read about Numpy linear algebra operations [here](https://numpy.org/doc/stable/reference/routines.linalg.html). 

### Exercise 1

Append array B1 to A1

**Hint**: Think about the commonly used Numpy functions.

In [30]:
A1 = np.array([1, 2, 3, 4, 5])
B1 = np.array([6, 7, 8, 9, 10])

### Your solution here

...

### Exercise 2

Find the *maximum* of the *flattened* array of matrix C2

Hint: Take a look at the [ndarray docs](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html)

In [34]:
C2 = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10]])

### Your solution here

...

Ellipsis

### Exercise 3

Find the *inner product* of matrices A3 and B3. 

**Hint**: Take a look at the [linalg docs](https://numpy.org/doc/stable/reference/routines.linalg.html). 

In [32]:
A3 = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10]])

B3 = np.array([[11, 12, 13, 14, 15],
             [16, 17, 18, 19, 20]])

### Your solution here

...

---

<a class="anchor" id="2"></a>
## Pandas Fundamentals
[Back to Table of Contents](#tof)

We'll just go ahead and continue into Pandas!

Pandas stands for "**Pan**el **Da**ta" (I know, not as good as NumPy). This is just referring to the tables, or **dataframes**, that Pandas works with. Dataframes are the most common and intuitive way for both humans and computers to organize data.

Being able to manipulate those dataframes is crucial for data scientists to be able to clean up their data in a way that is usable for analysis. 

This is where Pandas comes in.

We will talk about two main methods of cleaning our data to get ready for visualization:
1. [Filtering](#filtering)
2. [Grouping](#grouping)

But before learning the more techinical stuff, here's a quick introduction to Pandas.

In [ ]:
# the conventional Pandas import statement
import pandas as pd

There are 3 main functions for Pandas in the [data science life cycle](https://towardsdatascience.com/data-science-life-cycle-101-for-dummies-like-me-e66b47ad8d8f).

1. Reading in data
2. Summarizing the data
3. Cleaning the data  
    a. Stratify by grouping and filtering for certain subsets of the dataframe  
    b. Fill in or remove missing data  
    c. Combine various dataframes into a single dataframe  

For this workshop, we'll focus on the knowledge of Pandas that is helpful for creating great visualizations.

First, let's introduce the DataFrame and Series data types.  

A DataFrame is like a 2D table of information. Each row is called a **record or observation** because rows typically represent some real life event or object. And each column is called a **feature** because it's an aspect of the real life event or object.

In [ ]:
# Pandas reads in data and creates a DataFrame object of them
lib_traffic = pd.read_csv('data/HourlyTraffic-2019-12-11.csv')

# dataframe.head() returns the first 5 rows and all the columns of the dataframe
lib_traffic.head()

In the case of this dataset, each record represents an event -- the traffic of a specific location at a specific time. 


Each column represents a piece of information regarding each record.

In [ ]:
# a sanity check for the data type of lib_traffic
type(lib_traffic)

To grab certain parts of the dataframe, we can use slicing notation, similar to how we slice into Python lists or NumPy arrays. For a dataframe inside the variable `df`, we can slice like this:
```
df['column_name']
```
and it will give us a **Series**. <a class="anchor" id="series"></a>

A **Series** is a special data type that represents the column of a dataframe. A **Series** works very similar to a NumPy because it is *literally* a NumPy array with some extra functions built into it. More information about **Series** is always a Google search away, if you are interested in learning more about those extra functions.

[Back to Exercise 1](#ex1)

In [ ]:
# grabs the Entries column as a Series from the dataframe
lib_traffic['Entries'].head()

In [ ]:
# a sanity check for the data type of the Entries column
type(lib_traffic['Entries'])

In [ ]:
# Series behaving like a NumPy array
lib_traffic['Entries'][10:20]

In [ ]:
lib_traffic['Entries'][10:20] * 2

## Filtering with Pandas <a class="anchor" id="filtering"></a>
By filtering, we can remove data that we are uninterested in. Here are two main ideas we can use filtering for:
- keep data that fall within a range of values to narrow our scope for visualization
- remove faulty data or outliers that skew the perception of our visualizations

As we introduced in our last workshop, the most common format to filter data is as follows:
```
table_name[table_name[column] == value] # Only keep rows with this value in the selected column
table_name[table_name[column] != value] # Only keep rows WITHOUT this value in the selected column
table_name[table_name[column] > value] # Only keep rows with greater values in the selected column
```

[Jump to Exercise 3](#ex3)

For instance, given our library traffic dataset, let's say that we want the data that only pertains to Doe Library. First, let's look at the different facilities to see how to spell "Doe Library" exactly. This is important, because without the *exact* same spelling and capitaliation, Python will not recognize what you want, and will error or return the incorrect data.

In [ ]:
# one of the special functions that Series have is the `unique` function that gives all the unique values of a Series 
lib_traffic['Facility'].unique()

In [ ]:
# Notice that this returns an empty dataframe. Why? Because looking at the strings above, the `Doe` should be capitalized.
lib_traffic[lib_traffic['Facility'] == "Doe Library"]

In [ ]:
# again, but with proper capitalization
doe = lib_traffic[lib_traffic['Facility'] == "DOE Library"]
doe.head()

After we narrowed our data down to Doe Library, we can see that there are two different entrances to Doe, and that there is an entry for each hour of 12/11/19. Then, there should be 24 * 2 different entries.

In [ ]:
# sanity check for table size; `.shape` gives us the shape of the dataframe in the format (rows, column)
doe.shape

Here's a couple of other examples of things we can do with filtering.

In [ ]:
lib_traffic[lib_traffic['Entries'] > 300]

In [ ]:
lib_traffic[lib_traffic['Region'] == "UC Berkeley"].head()

In [ ]:
lib_traffic[lib_traffic['Region'] != "UC Berkeley"].head()

You may be wondering, what does the `NaN` mean? `NaN` is a common thing you will see with **missing/faulty data**. We won't talk about what to do with this, or how to take care of it, but just know that it is something to think about when working with a dataset.

---

You can also filter by multiple conditions by putting each condition in parentheses, and combining them with an ampersand (&). You can separate this into multiple lines, or just put it all together in the same line. For the sake of readibility, we put it in separate lines in this format example:
```
condition1 = table_name[column1] == value1
condition1 = table_name[column2] >= value2
table_name[(condition1) & (condition2)] # Only keep rows with both conditions satisfied
```

In [ ]:
condition1 = lib_traffic['Exits'] > 200
condition2 = lib_traffic['Entries'] > 200
lib_traffic[(condition1) & (condition2)]

In [ ]:
# both formats work, and generate the same result!
lib_traffic[(lib_traffic['Exits'] > 200) & (lib_traffic['Entries'] > 200)]

---
Now, as a final example, let's say we are trying to find the record with the largest number of entries at Doe. We can do this in two steps.

In [ ]:
# first, find the largest number in the `Entries` column
max_entries = np.max(doe['Entries'])

# then, find the row(s) that match `max_entries` in the Doe dataframe
doe[doe['Entries'] == max_entries]

From this single-record dataframe, we see that the time where there was the most entries into Doe Library on 12/11/19 was at 3pm.

In sum, using filtering, we can grab certain aspects of data that we want, and see more clearly specific points of interest. Later on, we will see how this can be useful for visualization.

## Grouping with Pandas <a class="anchor" id="grouping"></a>
By grouping, we can stratify our dataset by the unique values of a specific column in our dataset. Then, we can create visualizations based on the different stratas, and compare how they appear similar or different.

[Jump to Exercise 3](#ex3)

When we use the `groupby` function with Pandas, we will get a dataframe where:
- the column you specify to group by will become the index
- there will be 1 row for each unique value in the column
- every other column is aggregated by the function you choose

---

The syntax for groupby is as follows:
```
df.groupby(column).aggregation_function()
```
If we simply call `groupby` on our dataframe, it doesn't quite do anything yet. We get back a **groupby object**.

In [ ]:
lib_traffic.groupby('Facility')

From here, we can then aggregate by a specific function. There are a couple of common defaults built into groupby that we'll use today.
- sum: sums all the values of each column in the group
- mean: calculated the mean of all the values of each column in the group
- min:  same as above but minimum
- max: same as above but maximum
- count: counts the number of rows in the group

For example, we can group by `Facility` in order to get the sum number of people that enter and exit each library, regardless of which entrance.

In [ ]:
lib_traffic.groupby('Facility').sum()

Notice 2 things:
1. There is 1 row for each unique facility, as expected
2. Many of the columns disappeared. Why?

We're left with only 2 columns because those are the only columns where our aggregation function, summing, makes sense. It doesn't make sense to take the sum of a bunch of strings, or of a bunch of different dates, so Pandas automatically gets rid of them. Neat!

In [ ]:
lib_traffic.head()

In [ ]:
# some more examples; we add .head() to shorten the dataframe that is printed out
lib_traffic.groupby('Facility').mean().head()

In [ ]:
lib_traffic.groupby('Facility').min().head()

In [ ]:
lib_traffic.groupby('Facility').max().head()

In [ ]:
lib_traffic.groupby('Facility').count().head()

One last note:

You can groupby multiple columns! This creates a multi-index table, where each unique set of column values corresponds to a row in the table. The syntax is as follows:
```
df.groupby([column1, column2]).aggregation_function()
```

Let's group by `Date-Time` and `Facility` to see the total number of people entering __each library__ at __each hour__.

In [ ]:
total_lib_traffic = lib_traffic.groupby(["Date-Time", "Facility"]).sum()
total_lib_traffic

Here, the first index is all the unique date-times, and the second index is a repeated list of all the unique libraries that have a record for that date-time. So the number of rows is equal to (# unique date-times) * (# unique facilities). 

We can interpret the first row as "On 12/11/19, in the hour of 9:00am-10:00am, 6 people entered AHC Library."

#### Now we'll get into some Numpy and Pandas exercises! <a class="anchor" id="ex1"></a>

<a class="anchor" id="ex1"></a>
### Exercise 1

Calculate the minimum, maximum, average, and total number of people that entered any library.

Hint: We can get a NumPy array version of any column by using the Series syntax.


In [ ]:
### Your solution here

... 

<a class="anchor" id="2"></a>
## Exercise 2

Calculate the net sum number of people that entered each library at each hour.

*Hint*: net sum entered = Entries - Exits

*Hint2*: The sum of the resulting array should be 42.

In [ ]:
### Your solution here

... 

<a class="anchor" id="ex3"></a>
## Exercise 3

Create a dataframe from lib_traffic that has the total number of people that enter and exit any library at each time of the day.

In [ ]:
### Your solution here

... 

<a class="anchor" id="ex4"></a>
## Exercise 4

Create the same dataframe as above, but instead of any library, look only at the Engineering Library.

In [ ]:
### Your solution here

... 

<a class="anchor" id="ex5"></a>
## Exercise 5

Create a dataframe that has the maximum number of people that enter and exit each entrance.

In [ ]:
### Your solution here

... 

## Thanks for Coming! PLEASE COMPLETE THIS POST-WORKSHOP SURVEY!  
[Post-Workshop Survey Link Here](https://forms.gle/gfuYbKTFEscnkrMY8)

<a class="anchor" id="rs"></a>
### Reference Sheets!
[Back to Table of Contents](#tof)

Links updated as of 1/1/11.

- [NumPy Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)  
- [Pandas Cheat Sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)  
- [Matplotlib Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Python_Matplotlib_Cheat_Sheet.pdf)  
- [Seaborn Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Python_Seaborn_Cheat_Sheet.pdf)

### More Resources
1. Data Peer Consultants - That's us! We help undergrads and graduate students with projects, research, and more! Come to our drop-in hours.  
https://data.berkeley.edu/ds-peer-consulting

2. Towards Data Science - Website full of good blogs and helpful introductions to data science stuff.  
https://towardsdatascience.com/

3. Stack Overflow // Google - A great data scientist is adept at using StackOverflow and Google to find the answers to their bugs. More likely than not, someone out there has ran into the exact same problem as you, so might as well use their solutions as a resource!